# Generated by Django 4.0.4 on 2022-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrormirror', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcereview',
            name='resourcereview_stars',
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcereview',
            name='resourcereview_comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resourcereview',
            name='resourcereview_username',
            field=models.CharField(default='Anonymous', help_text='  ', max_length=255),
        ),
    ]
