# Generated by Django 4.0.4 on 2022-05-25 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrormirror', '0002_remove_resourcereview_resourcereview_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('user_name', models.CharField(default='Anonymous', help_text='  ', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, help_text='Date & Time Stamp')),
            ],
        ),
    ]
