# Generated by Django 4.0.3 on 2022-05-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrormirror', '0004_resourcereview_resourcereview_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcereview',
            name='resourcereview_stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
