# Generated by Django 4.0.3 on 2022-05-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrormirror', '0005_alter_resourcereview_resourcereview_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcereview',
            old_name='resourcereview_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resourcereview',
            old_name='resourcereview_comment',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='resourcereview',
            old_name='resourcereview_stars',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='resourcereview',
            old_name='resourcereview_username',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='websitereview',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
