# Generated by Django 4.0.3 on 2022-05-27 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrormirror', '0006_rename_resourcereview_date_resourcereview_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date & Time Stamp'),
        ),
        migrations.AlterField(
            model_name='resourcereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date & Time Stamp'),
        ),
        migrations.AlterField(
            model_name='resourcereview',
            name='user_name',
            field=models.CharField(default='Anonymous', help_text='  ', max_length=255),
        ),
        migrations.AlterField(
            model_name='websitereview',
            name='review',
            field=models.TextField(max_length=4000),
        ),
    ]
